### Get lan

GET http://localhost:7071/lan/4fef8286-99b9-46ac-b064-510e4bc8ba96
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIkFkbWluIiwiVXNlciJdLCJqdGkiOiJmZDAzMjA0ZC0zYjUzLTRlYjEtOWRjNy02YzY3ZTA4ZjhjZjQiLCJzcHVfaWQiOiIzNzYxMjk5MjU3ODAwNzg1OTIiLCJzcHVfbmljayI6Ildlb2wiLCJzcHVfYXZhdGFyIjoiZWExM2UwN2M3ZTljNDRjMjIwM2I1MjMxNjQwYzgyYzYiLCJuYmYiOjE2ODk3NjY5MzksImV4cCI6MTY5MjM1ODkzOSwiaWF0IjoxNjg5NzY2OTM5LCJpc3MiOiJENkE4Q0MxOEEwNTE2RjFDQzYxRDU2Nzc1NkU3NEZEQzZCQThCNUJBIiwiYXVkIjoiMzc2MTI5OTI1NzgwMDc4NTkyIn0.bWRn6AdsccQ_RJ-hTwe2I6zuHt_1AjAtXU1F-x-isuAip1IsR7-8DRwgdPpCdMHRAj2wd9U1eeAIrRVCusypq0awtROO0qXj3nYeShWEzU2ROFBBy_lYRl_3nBDBmJahn4Im9Uj7l8mYQWpNVnpmpcxkj9OVSatixegKV-021ona3QmmjY9xu9sNXw6hGJhoibDWsPq8ilHrvgWvq9SqPXGsaPHnksnfLVbtQQcOAdTopxh7W0RDEpwVlp6PNPYBE6iYrXOWon8-EW5CZEIpmagCmtWa-zACS-X5YTZcPUzExYn8hyk8bH87yU7mSYrQx4LwpMMWCuYvopy-SwttgQ

### Create new lan

POST http://localhost:7071/lan
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIkFkbWluIiwiVXNlciJdLCJqdGkiOiJmZDAzMjA0ZC0zYjUzLTRlYjEtOWRjNy02YzY3ZTA4ZjhjZjQiLCJzcHVfaWQiOiIzNzYxMjk5MjU3ODAwNzg1OTIiLCJzcHVfbmljayI6Ildlb2wiLCJzcHVfYXZhdGFyIjoiZWExM2UwN2M3ZTljNDRjMjIwM2I1MjMxNjQwYzgyYzYiLCJuYmYiOjE2ODk3NjY5MzksImV4cCI6MTY5MjM1ODkzOSwiaWF0IjoxNjg5NzY2OTM5LCJpc3MiOiJENkE4Q0MxOEEwNTE2RjFDQzYxRDU2Nzc1NkU3NEZEQzZCQThCNUJBIiwiYXVkIjoiMzc2MTI5OTI1NzgwMDc4NTkyIn0.bWRn6AdsccQ_RJ-hTwe2I6zuHt_1AjAtXU1F-x-isuAip1IsR7-8DRwgdPpCdMHRAj2wd9U1eeAIrRVCusypq0awtROO0qXj3nYeShWEzU2ROFBBy_lYRl_3nBDBmJahn4Im9Uj7l8mYQWpNVnpmpcxkj9OVSatixegKV-021ona3QmmjY9xu9sNXw6hGJhoibDWsPq8ilHrvgWvq9SqPXGsaPHnksnfLVbtQQcOAdTopxh7W0RDEpwVlp6PNPYBE6iYrXOWon8-EW5CZEIpmagCmtWa-zACS-X5YTZcPUzExYn8hyk8bH87yU7mSYrQx4LwpMMWCuYvopy-SwttgQ
Content-Type: application/json

{
  "id": "4fef8286-99b9-46ac-b064-510e4bc8ba96",
  "title": "saltenlan",
  "background": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjEiIHdpZHRoPSI0NDFweCIgaGVpZ2h0PSI4MDFweCIgdmlld0JveD0iLTAuNSAtMC41IDQ0MSA4MDEiIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7Ij48ZGVmcz48c3R5bGUgdHlwZT0idGV4dC9jc3MiPkBpbXBvcnQgdXJsKGh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20vY3NzP2ZhbWlseT1BcmNoaXRlY3RzK0RhdWdodGVyKTsmI3hhOzwvc3R5bGU+PC9kZWZzPjxnPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSI0NDAiIGhlaWdodD0iODAwIiBmaWxsPSIjY2NjY2ZmIiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiLz48L2c+PC9zdmc+"
}


### Change lan title

PUT http://localhost:7071/lan/4fef8286-99b9-46ac-b064-510e4bc8ba96
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIkFkbWluIiwiVXNlciJdLCJqdGkiOiJmZDAzMjA0ZC0zYjUzLTRlYjEtOWRjNy02YzY3ZTA4ZjhjZjQiLCJzcHVfaWQiOiIzNzYxMjk5MjU3ODAwNzg1OTIiLCJzcHVfbmljayI6Ildlb2wiLCJzcHVfYXZhdGFyIjoiZWExM2UwN2M3ZTljNDRjMjIwM2I1MjMxNjQwYzgyYzYiLCJuYmYiOjE2ODk3NjY5MzksImV4cCI6MTY5MjM1ODkzOSwiaWF0IjoxNjg5NzY2OTM5LCJpc3MiOiJENkE4Q0MxOEEwNTE2RjFDQzYxRDU2Nzc1NkU3NEZEQzZCQThCNUJBIiwiYXVkIjoiMzc2MTI5OTI1NzgwMDc4NTkyIn0.bWRn6AdsccQ_RJ-hTwe2I6zuHt_1AjAtXU1F-x-isuAip1IsR7-8DRwgdPpCdMHRAj2wd9U1eeAIrRVCusypq0awtROO0qXj3nYeShWEzU2ROFBBy_lYRl_3nBDBmJahn4Im9Uj7l8mYQWpNVnpmpcxkj9OVSatixegKV-021ona3QmmjY9xu9sNXw6hGJhoibDWsPq8ilHrvgWvq9SqPXGsaPHnksnfLVbtQQcOAdTopxh7W0RDEpwVlp6PNPYBE6iYrXOWon8-EW5CZEIpmagCmtWa-zACS-X5YTZcPUzExYn8hyk8bH87yU7mSYrQx4LwpMMWCuYvopy-SwttgQ
Content-Type: application/json

{
  "id": "4fef8286-99b9-46ac-b064-510e4bc8ba96",
  "title": "saltenlan 3"
}

### Change lan background

PUT http://localhost:7071/lan/4fef8286-99b9-46ac-b064-510e4bc8ba96
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIkFkbWluIiwiVXNlciJdLCJqdGkiOiJmZDAzMjA0ZC0zYjUzLTRlYjEtOWRjNy02YzY3ZTA4ZjhjZjQiLCJzcHVfaWQiOiIzNzYxMjk5MjU3ODAwNzg1OTIiLCJzcHVfbmljayI6Ildlb2wiLCJzcHVfYXZhdGFyIjoiZWExM2UwN2M3ZTljNDRjMjIwM2I1MjMxNjQwYzgyYzYiLCJuYmYiOjE2ODk3NjY5MzksImV4cCI6MTY5MjM1ODkzOSwiaWF0IjoxNjg5NzY2OTM5LCJpc3MiOiJENkE4Q0MxOEEwNTE2RjFDQzYxRDU2Nzc1NkU3NEZEQzZCQThCNUJBIiwiYXVkIjoiMzc2MTI5OTI1NzgwMDc4NTkyIn0.bWRn6AdsccQ_RJ-hTwe2I6zuHt_1AjAtXU1F-x-isuAip1IsR7-8DRwgdPpCdMHRAj2wd9U1eeAIrRVCusypq0awtROO0qXj3nYeShWEzU2ROFBBy_lYRl_3nBDBmJahn4Im9Uj7l8mYQWpNVnpmpcxkj9OVSatixegKV-021ona3QmmjY9xu9sNXw6hGJhoibDWsPq8ilHrvgWvq9SqPXGsaPHnksnfLVbtQQcOAdTopxh7W0RDEpwVlp6PNPYBE6iYrXOWon8-EW5CZEIpmagCmtWa-zACS-X5YTZcPUzExYn8hyk8bH87yU7mSYrQx4LwpMMWCuYvopy-SwttgQ
Content-Type: application/json

{
  "id": "4fef8286-99b9-46ac-b064-510e4bc8ba96",
  "background": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjEiIHdpZHRoPSI0NDFweCIgaGVpZ2h0PSI4MDFweCIgdmlld0JveD0iLTAuNSAtMC41IDQ0MSA4MDEiIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7Ij48ZGVmcz48c3R5bGUgdHlwZT0idGV4dC9jc3MiPkBpbXBvcnQgdXJsKGh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20vY3NzP2ZhbWlseT1BcmNoaXRlY3RzK0RhdWdodGVyKTsmI3hhOzwvc3R5bGU+PC9kZWZzPjxnPjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSI0NDAiIGhlaWdodD0iODAwIiBmaWxsPSIjY2NjY2ZmIiBzdHJva2U9Im5vbmUiIHBvaW50ZXItZXZlbnRzPSJhbGwiLz48L2c+PC9zdmc+"
}