
### Login with discord token

POST http://localhost:7071/discord/login
Content-Type: application/json

{ "token" : "5PZvcJvi6PziLvfg8npMpM3V6lTy1l" }

### Renew with refresh token

POST http://localhost:7071/discord/renew
Content-Type: application/json

{
  "refreshToken": "XxdCP33Calzyh17r6IAmChBcJtHBiA"
}