name: Deploy template

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy infrastructure
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
      - name: Run template deployment
        uses: azure/arm-deploy@v1.0.9
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: ./Infrastructure/master.bicep
